services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose --version

jobs:
  include:
    - stage: lint
      language: node_js
      node_js:
        - '8'
      cache:
        directories:
          - node_modules
      script: eslint .
    - stage: test
      script: cd ./backend && make test