services:
  - docker

jobs:
  include:
    # - stage: lint
    #   language: node_js
    #   node_js:
    #     - '8'
    #   cache:
    #     directories:
    #       - node_modules
    #   script: eslint .
    - stage: Test backend
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
      script:
        - |
          make -C ./backend test && \
          make -C ./backend release && \
          make -C ./backend tag latest `git rev-parse --short HEAD` `git tag --points-at HEAD` && \
          make -C ./backend buildtag master `git tag --points-at HEAD` && \
          make -C ./backend login && \
          make -C ./backend publish && \

      after_script:
        - make -C ./backend clean
        - make -C ./backend logout