services:
  - docker
jobs:
  include:
    - stage: Lint
      language: node_js
      node_js:
        - '8'
      cache:
        directories:
          - node_modules
      script: eslint .
    - stage: Test and release app backend
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
      script:
        - |
          make test && \
          make release && \
          make tag latest `git rev-parse --short HEAD` `git tag --points-at HEAD` && \
          make buildtag master `git tag --points-at HEAD` && \
          make login && \
          make publish

      after_script:
        - make clean
        - make logout

deploy:
  provider: script
  script: make -C ./backend deploy
  on:
    branch: deploy