version: '3'

services:
  db:
    image:
      postgres:10.5-alpine
    environment:
      - POSTGRES_PASSWORD=qwerty123

  db_probe:
    image: trolleksii/ansible_db_probe
    depends_on:
      - db
    environment:
      - PROBE_HOST=db
      - PROBE_PORT=5432

  app:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDB=postgres
      - PGPASSWORD=qwerty123
      - PGPORT=5432
      - JWT_SECRET=SIMPLE_SECRET_FOR_TEST
      - JWT_EXP_THRESHOLD=1 day
    ports:
      - "8000:8000"
    depends_on:
      - db