version: '3'

services:
  db:
    image:
      postgres:10.5-alpine
    environment:
      - POSTGRES_PASSWORD=qwerty123

  db_probe:
    image: trolleksii/ansible_db_probe
    depends_on:
      - db
    environment:
      - PROBE_HOST=db
      - PROBE_PORT=5432

  backend:
    build:
      context: ../../
      dockerfile: ./docker/release/Dockerfile
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDB=postgres
      - PGPASSWORD=qwerty123
      - PGPORT=5432
      - DATABASE_URL=postgres://postgres:qwerty123@db:5432/postgres
      - JWT_SECRET=SIMPLE_SECRET_FOR_TEST
      - JWT_EXP_THRESHOLD=1 day
    depends_on:
      - db
    ports:
      - "8000:8000"

  test:
    build:
      context: ../../
      dockerfile: ./docker/release/Dockerfile-integration
    environment:
      - API_URL=http://backend:8000/api/
    depends_on:
      - backend

  frontend:
    build:
      context: ../../
      dockerfile: ./docker/release/Dockerfile-frontend
    ports:
      - "80:80"
      - "443:443"