module.exports = `('Tokyo','Japan'),
('New York','United States'),
('Mexico City','Mexico'),
('Mumbai','India'),
('Sao Paulo','Brazil'),
('Delhi','India'),
('Shanghai','China'),
('Kolkata','India'),
('Dhaka','Bangladesh'),
('Buenos Aires','Argentina'),
('Los Angeles','United States'),
('Karachi','Pakistan'),
('Cairo','Egypt'),
('Rio de Janeiro','Brazil'),
('Osaka','Japan'),
('Beijing','China'),
('Manila','Philippines'),
('Moscow','Russia'),
('Istanbul','Turkey'),
('Paris','France'),
('Seoul','Korea South'),
('Lagos','Nigeria'),
('Jakarta','Indonesia'),
('Guangzhou','China'),
('Chicago','United States'),
('London','United Kingdom'),
('Lima','Peru'),
('Tehran','Iran'),
('Kinshasa','Congo (Kinshasa)'),
('Bogota','Colombia'),
('Shenzhen','China'),
('Wuhan','China'),
('Hong Kong','Hong Kong'),
('Tianjin','China'),
('Chennai','India'),
('Taipei','Taiwan'),
('Bangalore','India'),
('Bangkok','Thailand'),
('Lahore','Pakistan'),
('Chongqing','China'),
('Hyderabad','India'),
('Miami','United States'),
('Santiago','Chile'),
('Dallas','United States'),
('Philadelphia','United States'),
('Belo Horizonte','Brazil'),
('Madrid','Spain'),
('Houston','United States'),
('Ahmedabad','India'),
('Ho Chi Minh City','Vietnam'),
('Singapore','Singapore'),
('Luanda','Angola'),
('Atlanta','United States'),
('Baghdad','Iraq'),
('Barcelona','Spain'),
('Haora','India'),
('Shenyeng','China'),
('Khartoum','Sudan'),
('Pune','India'),
('Sydney','Australia'),
('Boston','United States'),
('St. Petersburg','Russia'),
('Chittagong','Bangladesh'),
('Dongguan','China'),
('Riyadh','Saudi Arabia'),
('Hanoi','Vietnam'),
('Guadalajara','Mexico'),
('Melbourne','Australia'),
('Alexandria','Egypt'),
('Chengdu','China'),
('Rangoon','Burma'),
('Phoenix','United States'),
('Xian','China'),
('Porto Alegre','Brazil'),
('Surat','India'),
('Hechi','China'),
('Abidjan','C𴥠DӉvoire'),
('Brasilia','Brazil'),
('Ankara','Turkey'),
('Monterrey','Mexico'),
('Yokohama','Japan'),
('Nanjing','China'),
('Montreal','Canada'),
('Guiyang','China'),
('Recife','Brazil'),
('Harbin','China'),
('Fortaleza','Brazil'),
('San Francisco','United States'),
('Seattle','United States'),
('Zhangzhou','China'),
('Detroit','United States'),
('Salvador','Brazil'),
('Busan','Korea South'),
('Johannesburg','South Africa'),
('Berlin','Germany'),
('Algiers','Algeria'),
('Rome','Italy'),
('Pyongyang','Korea North'),
('Medellin','Colombia'),
('Kabul','Afghanistan'),
('Athens','Greece'),
('Nagoya','Japan'),
('Cape Town','South Africa'),
('Changchun','China'),
('San Diego','United States'),
('Casablanca','Morocco'),
('Dalian','China'),
('Kanpur','India'),
('Kano','Nigeria'),
('Tel Aviv-Yafo','Israel'),
('Addis Ababa','Ethiopia'),
('Curitiba','Brazil'),
('Zibo','China'),
('Jeddah','Saudi Arabia'),
('Nairobi','Kenya'),
('Hangzhou','China'),
('Benoni','South Africa'),
('Caracas','Venezuela'),
('Milan','Italy'),
('Stuttgart','Germany'),
('Kunming','China'),
('Dar es Salaam','Tanzania'),
('Jaipur','India'),
('Taiyuan','China'),
('Frankfurt','Germany'),
('Minneapolis','United States'),
('Qingdao','China'),
('Surabaya','Indonesia'),
('Lisbon','Portugal'),
('Jinan','China'),
('Fukuoka','Japan'),
('Campinas','Brazil'),
('Kaohsiung','Taiwan'),
('Quezon City','Philippines'),
('Katowice','Poland'),
('Tampa','United States'),
('Denver','United States'),
('Aleppo','Syria'),
('Durban','South Africa'),
('Kiev','Ukraine'),
('Lucknow','India'),
('El Giza','Egypt'),
('Zhengzhou','China'),
('Taichung','Taiwan'),
('Brooklyn','United States'),
('Ibadan','Nigeria'),
('Faisalabad','Pakistan'),
('Fuzhou','China'),
('Dakar','Senegal'),
('Changsha','China'),
('Izmir','Turkey'),
('Xiangtan','China'),
('Lanzhou','China'),
('Incheon','Korea South'),
('Sapporo','Japan'),
('Xiamen','China'),
('Guayaquil','Ecuador'),
('George Town','Malaysia'),
('Mashhad','Iran'),
('Damascus','Syria'),
('Daegu','Korea South'),
('Nagpur','India'),
('Jinxi','China'),
('Shijianzhuang','China'),
('Tunis','Tunisia'),
('Vienna','Austria'),
('Jilin','China'),
('Omdurman','Sudan'),
('Bandung','Indonesia'),
('Bekasi','Indonesia'),
('Mannheim','Germany'),
('Nanchang','China'),
('Wenzhou','China'),
('Queens','United States'),
('Vancouver','Canada'),
('Birmingham','United Kingdom'),
('Cali','Colombia'),
('Naples','Italy'),
('Sendai','Japan'),
('Manchester','United Kingdom'),
('Puebla','Mexico'),
('Tripoli','Libya'),
('Tashkent','Uzbekistan'),
('Baltimore','United States'),
('Nanchong','China'),
('Havana','Cuba'),
('Belem','Brazil'),
('Nanning','China'),
('Patna','India'),
('Santo Domingo','Dominican Republic'),
('Urumqi','China'),
('Zaozhuang','China'),
('Baku','Azerbaijan'),
('Accra','Ghana'),
('Yantai','China'),
('Medan','Indonesia'),
('Santa Cruz','Bolivia'),
('Saint Louis','United States'),
('Xuzhou','China'),
('Linyi','China'),
('Maracaibo','Venezuela'),
('Riverside','United States'),
('Kuwait','Kuwait'),
('Ad Damman','Saudi Arabia'),
('Haikou','China'),
('Hiroshima','Japan'),
('Las Vegas','United States'),
('Baotou','China'),
('Hefei','China'),
('Portland','United States'),
('Indore','India'),
('Goiania','Brazil'),
('Sanaa','Yemen'),
('Port-au-Prince','Haiti'),
('San Antonio','United States'),
('Haiphong','Vietnam'),
('Suzhou','China'),
('Nanyang','China'),
('Bucharest','Romania'),
('Ningbo','China'),
('Douala','Cameroon'),
('Tangshan','China'),
('Tainan','Taiwan'),
('Datong','China'),
('Asuncion','Paraguay'),
('Saidu','Pakistan'),
('Brisbane','Australia'),
('Rawalpindi','Pakistan'),
('Beirut','Lebanon'),
('Sacramento','United States'),
('Minsk','Belarus'),
('Kyoto','Japan'),
('San Jose','United States'),
('Barranquilla','Colombia'),
('Valencia','Venezuela'),
('Shuyang','China'),
('Orlando','United States'),
('Hamburg','Germany'),
('Vadodara','India'),
('Manaus','Brazil'),
('Shangqiu','China'),
('Wuxi','China'),
('Palembang','Indonesia'),
('Brussels','Belgium'),
('Essen','Germany'),
('Cleveland','United States'),
('Bhopal','India'),
('Hohhot','China'),
('Pittsburgh','United States'),
('Luoyang','China'),
('Santos','Brazil'),
('Jianmen','China'),
('Warsaw','Poland'),
('Rabat','Morocco'),
('Vitoria','Brazil'),
('Quito','Ecuador'),
('Antananarivo','Madagascar'),
('Coimbatore','India'),
('Daqing','China'),
('Luan','China'),
('Wanzhou','China'),
('Budapest','Hungary'),
('Turin','Italy'),
('Ludhiana','India'),
('Kumasi','Ghana'),
('Manhattan','United States'),
('Qiqihar','China'),
('Anshan','China'),
('Cincinnati','United States'),
('Austin','United States'),
('Zhongli','Taiwan'),
('Handan','China'),
('Taian','China'),
('Isfahan','Iran'),
('Yaounde','Cameroon'),
('Shantou','China'),
('Agra','India'),
('Kansas City','United States'),
('La Paz','Bolivia'),
('Zhanjiang','China'),
('Kalyan','India'),
('Abuja','Nigeria'),
('Harare','Zimbabwe'),
('Xiantao','China'),
('Tijuana','Mexico'),
('Khulna','Bangladesh'),
('Weifang','China'),
('Santiago','Dominican Republic'),
('Indianapolis','United States'),
('Xinyang','China'),
('Luzhou','China'),
('Perth','Australia'),
('Toluca','Mexico'),
('Leeds','United Kingdom'),
('Vishakhapatnam','India'),
('Kobe','Japan'),
('Multan','Pakistan'),
('Kochi','India'),
('Gujranwala','Pakistan'),
('Montevideo','Uruguay'),
('Niteroi','Brazil'),
('Ganzhou','China'),
('Florence','Italy'),
('Liuzhou','China'),
('Columbus','United States'),
('Bamako','Mali'),
('Conakry','Guinea'),
('Bursa','Turkey'),
('Leon','Mexico'),
('Virginia Beach','United States'),
('Nasik','India'),
('Fushun','China'),
('Changde','China'),
('Daejeon','Korea South'),
('Neijiang','China'),
('Phnom Penh','Cambodia'),
('Quanzhou','China'),
('Kharkiv','Ukraine'),
('Hyderabad','Pakistan'),
('Bronx','United States'),
('Lome','Togo'),
('Cordoba','Argentina'),
('Huainan','China'),
('Doha','Qatar'),
('Kuala Lumpur','Malaysia'),
('Maputo','Mozambique'),
('Kaduna','Nigeria'),
('Gwangju','Korea South'),
('Charlotte','United States'),
('Kawasaki','Japan'),
('San Salvador','El Salvador'),
('Suining','China'),
('Lyon','France'),
('Karaj','Iran'),
('Kampala','Uganda'),
('Tabriz','Iran'),
('The Hague','Netherlands'),
('Davao','Philippines'),
('Marseille','France'),
('Meerut','India'),
('Mianyang','China'),
('Semarang','Indonesia'),
('Faridabad','India'),
('Novosibirsk','Russia'),
('Makkah','Saudi Arabia'),
('Dubai','United Arab Emirates'),
('Auckland','New Zealand'),
('Milwaukee','United States'),
('Maanshan','China'),
('Brazzaville','Congo (Brazzaville)'),
('Lubumbashi','Congo (Kinshasa)'),
('Yiyang','China'),
('Varanasi','India'),
('Ciudad Juarez','Mexico'),
('Ghaziabad','India'),
('Pretoria','South Africa'),
('Heze','China'),
('Porto','Portugal'),
('Lusaka','Zambia'),
('Asansol','India'),
('Changzhou','China'),
('Mosul','Iraq'),
('Yekaterinburg','Russia'),
('Peshawar','Pakistan'),
('Mandalay','Burma'),
('Jamshedpur','India'),
('Mbuji-Mayi','Congo (Kinshasa)'),
('Madurai','India'),
('Adana','Turkey'),
('Sheffield','United Kingdom'),
('Jabalpur','India'),
('San Jose','Costa Rica'),
('Panama City','Panama'),
('Nizhny Novgorod','Russia'),
('Chifeng','China'),
('Duisburg','Germany'),
('Munich','Germany'),
('Stockholm','Sweden'),
('Huaiyin','China'),
('Ujungpandang','Indonesia'),
('Rajkot','India'),
('Dhanbad','India'),
('Mudangiang','China'),
('Geneva','Switzerland'),
('Shiraz','Iran'),
('Huzhou','China'),
('Tianshui','China'),
('Lupanshui','China'),
('Dusseldorf','Germany'),
('Maoming','China'),
('Seville','Spain'),
('Amritsar','India'),
('Vila Velha','Brazil'),
('Almaty','Kazakhstan'),
('Warangal','India'),
('Rosario','Argentina'),
('Allahabad','India'),
('Providence','United States'),
('Benin City','Nigeria'),
('Maceio','Brazil'),
('Jining','China'),
('Sofia','Bulgaria'),
('Abbottabad','Pakistan'),
('Banghazi','Libya'),
('Cilacap','Indonesia'),
('Prague','Czechia'),
('Glasgow','United Kingdom'),
('Leshan','China'),
('Ouagadougou','Burkina Faso'),
('Adelaide','Australia'),
('Ottawa','Canada'),
('Shangrao','China'),
('Torreon','Mexico'),
('Jacksonville','United States'),
('Srinagar','India'),
('Samara','Russia'),
('Vijayawada','India'),
('Omsk','Russia'),
('Newcastle','Australia'),
('Yulin','China'),
('Nampo','Korea North'),
('Xianyang','China'),
('Cagayan de Oro','Philippines'),
('Can Tho','Vietnam'),
('Barquisimeto','Venezuela'),
('Kazan','Russia'),
('Helsinki','Finland'),
('Aurangabad','India'),
('Calgary','Canada'),
('Nezahualcoyotl','Mexico'),
('Zurich','Switzerland'),
('Baoding','China'),
('Zigong','China'),
('Sharjah','United Arab Emirates'),
('Yerevan','Armenia'),
('Mogadishu','Somalia'),
('Huambo','Angola'),
('Ankang','China'),
('Tbilisi','Georgia'),
('Ikare','Nigeria'),
('Belgrade','Serbia'),
('Bhilai','India'),
('Jinhua','China'),
('Chelyabinsk','Russia'),
('Dushanbe','Tajikistan'),
('Kobenhavn','Denmark'),
('Changwon','Korea South'),
('Zhuzhou','China'),
('Suwon','Korea South'),
('Vereeniging','South Africa'),
('Memphis','United States'),
('Xiangfan','China'),
('Nashville','United States'),
('Salt Lake City','United States'),
('Ulsan','Korea South'),
('Zhucheng','China'),
('Amman','Jordan'),
('Dublin','Ireland'),
('Edmonton','Canada'),
('Sholapur','India'),
('Rostov','Russia'),
('Dnipro','Ukraine'),
('Xining','China'),
('Zhangjiakou','China'),
('Gaziantep','Turkey'),
('Lille','France'),
('Ranchi','India'),
('Richmond','United States'),
('Monrovia','Liberia'),
('Sao Luis','Brazil'),
('Amsterdam','Netherlands'),
('Jerusalem','Israel'),
('New Orleans','United States'),
('Guatemala','Guatemala'),
('Florianopolis','Brazil'),
('Zhuhai','China'),
('Port Elizabeth','South Africa'),
('Port Harcourt','Nigeria'),
('Jiamusi','China'),
('Ufa','Russia'),
('Hengyang','China'),
('Benxi','China'),
('Haifa','Israel'),
('Medina','Saudi Arabia'),
('Bucaramanga','Colombia'),
('Maracay','Venezuela'),
('Raleigh','United States'),
('Rotterdam','Netherlands'),
('Hims','Syria'),
('Cologne','Germany'),
('Louisville','United States'),
('Qinhuangdao','China'),
('Fez','Morocco'),
('Aden','Yemen'),
('Da Nang','Vietnam'),
('Cochabamba','Bolivia'),
('Yongzhou','China'),
('Baoshan','China'),
('Kitakyushu','Japan'),
('Perm','Russia'),
('Ahvaz','Iran'),
('Jodhpur','India'),
('San Luis Potosi','Mexico'),
('Odessa','Ukraine'),
('Yinchuan','China'),
('Ndjamena','Chad'),
('Donetsk','Ukraine'),
('Joinville','Brazil'),
('Jiaxing','China'),
('Guilin','China'),
('Dahuk','Iraq'),
('Volgograd','Russia'),
('Guwahati','India'),
('Yangquan','China'),
('Natal','Brazil'),
('Chandigarh','India'),
('Gwalior','India'),
('Hamamatsu','Japan'),
('Qom','Iran'),
('Merida','Mexico'),
('Jixi','China'),
('Xinyi','China'),
('Queretaro','Mexico'),
('Pingxiang','China'),
('Kelang','Malaysia'),
('Joao Pessoa','Brazil'),
('Jinzhou','China'),
('Salerno','Italy'),
('Thiruvananthapuram','India'),
('Kozhikode','India'),
('Ogbomosho','Nigeria'),
('Tiruchirappalli','India'),
('General Santos','Philippines'),
('Hue','Vietnam'),
('Bacolod','Philippines'),
('Oklahoma City','United States'),
('Nantong','China'),
('Tegucigalpa','Honduras'),
('Foshan','China'),
('Songnam','Korea South'),
('Kingston','Jamaica'),
('Bridgeport','United States'),
('Naypyidaw','Burma'),
('Nice','France'),
('Irbil','Iraq'),
('Krasnoyarsk','Russia'),
('Djibouti','Djibouti'),
('Olinda','Brazil'),
('Buffalo','United States'),
('Managua','Nicaragua'),
('Antwerpen','Belgium'),
('Konya','Turkey'),
('Bogor','Indonesia'),
('Niamey','Niger'),
('Hartford','United States'),
('Xinyu','China'),
('Huaibei','China'),
('Teresina','Brazil'),
('Naha','Japan'),
('Xinxiang','China'),
('Goyang','Korea South'),
('Yibin','China'),
('Aba','Nigeria'),
('Maiduguri','Nigeria'),
('Tirana','Albania'),
('Kathmandu','Nepal'),
('Az Zarqa','Jordan'),
('Tarsus','Turkey'),
('Bengbu','China'),
('Mendoza','Argentina'),
('Hubli','India'),
('Concepcion','Chile'),
('Zaria','Nigeria'),
('Anyang','China'),
('Cartagena','Colombia'),
('Mysore','India'),
('Ulaanbaatar','Mongolia'),
('Mexicali','Mexico'),
('Tongliao','China'),
('Newcastle','United Kingdom'),
('Mombasa','Kenya'),
('Novo Hamburgo','Brazil'),
('Callao','Peru'),
('Bilbao','Spain'),
('Johor Bahru','Malaysia'),
('Yichang','China'),
('Raipur','India'),
('Salem','India'),
('Yangjiang','China'),
('Marrakesh','Morocco'),
('Kaifeng','China'),
('Dandong','China'),
('Basra','Iraq'),
('Aguascalientes','Mexico'),
('Okayama','Japan'),
('Xuanzhou','China'),
('Puchon','Korea South'),
('Rizhao','China'),
('Bandar Lampung','Indonesia'),
('Palermo','Italy'),
('Cardiff','United Kingdom'),
('Tucson','United States'),
('Kigali','Rwanda'),
('Tampico','Mexico'),
('Jiaozuo','China'),
('Padang','Indonesia'),
('Jullundur','India'),
('Fort Worth','United States'),
('Valparaiso','Chile'),
('Zhenjiang','China'),
('Zunyi','China'),
('Anshun','China'),
('Pingdingshan','China'),
('Toulouse','France'),
('El Paso','United States'),
('Nova Iguacu','Brazil'),
('Voronezh','Russia'),
('Bhubaneshwar','India'),
('Saratov','Russia'),
('Yuci','China'),
('Yancheng','China'),
('Bishkek','Kyrgyzstan'),
('Honolulu','United States'),
('Oslo','Norway'),
('Cuernavaca','Mexico'),
('Linfen','China'),
('Bangui','Central African Republic'),
('Warri','Nigeria'),
('Tucuman','Argentina'),
('Basel','Switzerland'),
('Kermanshah','Iran'),
('Thessaloniki','Greece'),
('Freetown','Sierra Leone'),
('Kota','India'),
('Braga','Portugal'),
('Jhansi','India'),
('Yueyang','China'),
('Nottingham','United Kingdom'),
('Agadir','Morocco'),
('Butterworth','Malaysia'),
('Bareilly','India'),
('Jos','Nigeria'),
('Xingyi','China'),
('Arequipa','Peru'),
('Cebu','Philippines'),
('Liverpool','United Kingdom'),
('Rajshahi','Bangladesh'),
('Langfang','China'),
('Wuhu','China'),
('Culiacan','Mexico'),
('Zhaotang','China'),
('Valencia','Spain'),
('Cuiaba','Brazil'),
('Lingyuan','China'),
('Qui Nhon','Vietnam'),
('Malang','Indonesia'),
('Aligarh','India'),
('Lvov','Ukraine'),
('Bordeaux','France'),
('Baoji','China'),
('Pekanbaru','Indonesia'),
('McAllen','United States'),
('Oran','Algeria'),
('Yingkow','China'),
('Bhiwandi','India'),
('Liaoyang','China'),
('Chihuahua','Mexico'),
('Omaha','United States'),
('Jammu','India'),
('Malacca','Malaysia'),
('Zaporizhzhya','Ukraine'),
('Moradabad','India'),
('Antalya','Turkey'),
('Al Hudaydah','Yemen'),
('Islamabad','Pakistan'),
('Campo Grande','Brazil'),
('Shaoxing','China'),
('Yichun','China'),
('Mangalore','India'),
('Wuppertal','Germany'),
('Cheongju','Korea South'),
('Zamboanga','Philippines'),
('Hamhung','Korea North'),
('Ilorin','Nigeria'),
('Fuyang','China'),
('Saarbrucken','Germany'),
('Fuxin','China'),
('Shiyan','China'),
('Quetta','Pakistan'),
('Trujillo','Peru'),
('Kananga','Congo (Kinshasa)'),
('Trabzon','Turkey'),
('Cotonou','Benin'),
('Jincheng','China'),
('Albuquerque','United States'),
('Lodz','Poland'),
('Krakow','Poland'),
('Vientiane','Laos'),
('Saltillo','Mexico'),
('Sao Jose dos Campos','Brazil'),
('Hungnam','Korea North'),
('Taizz','Yemen'),
('Pietermaritzburg','South Africa'),
('Tangier','Morocco'),
('Changhua','Taiwan'),
('Hsinchu','Taiwan'),
('Fargona','Uzbekistan'),
('Namangan','Uzbekistan'),
('Kolhapur','India'),
('Birmingham','United States'),
('Liege','Belgium'),
('Ciudad Guayana','Venezuela'),
('Hegang','China'),
('Riga','Latvia'),
('Nouakchott','Mauritania'),
('Naga','Philippines'),
('Gdansk','Poland'),
('Ansan','Korea South'),
('Nurnberg','Germany'),
('Oyo','Nigeria'),
('Muscat','Oman'),
('Amravati','India'),
('Denpasar','Indonesia'),
('Sokoto','Nigeria'),
('Beihai','China'),
('Ashgabat','Turkmenistan'),
('Bremen','Germany'),
('As Sulaymaniyah','Iraq'),
('Zagreb','Croatia'),
('Hannover','Germany'),
('Cucuta','Colombia'),
('Hamilton','Canada'),
('Moshi','Tanzania'),
('Shaoguan','China'),
('Dayton','United States'),
('Kumamoto','Japan'),
('Lianyungang','China'),
('Acapulco','Mexico'),
('Kandahar','Afghanistan'),
('Rochester','United States'),
('Dehra Dun','India'),
('Jeonju','Korea South'),
('Samarqand','Uzbekistan'),
('Qingyuan','China'),
('Changzhi','China'),
('Tolyatti','Russia'),
('Jaboatao','Brazil'),
('Shizuoka','Japan'),
('Sarasota','United States'),
('Bulawayo','Zimbabwe'),
('Soledad','Colombia'),
('Meknes','Morocco'),
('Sarajevo','Bosnia And Herzegovina'),
('La Plata','Argentina'),
('Fresno','United States'),
('Malegaon','India'),
('Enugu','Nigeria'),
('Chisinau','Moldova'),
('Huangshi','China'),
('Aracaju','Brazil'),
('Bonn','Germany'),
('San Pedro Sula','Honduras'),
('Allentown','United States'),
('Nellore','India'),
('Catania','Italy'),
('Gorakhpur','India'),
('Tulsa','United States'),
('Ipoh','Malaysia'),
('Chongjin','Korea North'),
('Utsunomiya','Japan'),
('Puyang','China'),
('An Najaf','Iraq'),
('Sao Jose dos Pinhais','Brazil'),
('Santo Andre','Brazil'),
('Bytom','Poland'),
('Pointe-Noire','Congo (Brazzaville)'),
('At Taif','Saudi Arabia'),
('Ismailia','Egypt'),
('Shimoga','India'),
('Bien Hoa','Vietnam'),
('Zhanyi','China'),
('Kryvyy Rih','Ukraine'),
('Andijon','Uzbekistan'),
('Tiruppur','India'),
('Irbid','Jordan'),
('Krasnodar','Russia'),
('Concord','United States'),
('Zaragoza','Spain'),
('Genoa','Italy'),
('Lilongwe','Malawi'),
('Diyarbakir','Turkey'),
('Morelia','Mexico'),
('Ulyanovsk','Russia'),
('Utrecht','Netherlands'),
('Kikwit','Congo (Kinshasa)'),
('Al Hufuf','Saudi Arabia'),
('Yogyakarta','Indonesia'),
('Wroclaw','Poland'),
('Winnipeg','Canada'),
('Izhevsk','Russia'),
('Zhuozhou','China'),
('Raurkela','India'),
('Springfield','United States'),
('Colorado Springs','United States'),
('Quebec','Canada'),
('Poznan','Poland'),
('Bur Said','Egypt'),
('Nanded','India'),
('Bannu','Pakistan'),
('Asmara','Eritrea'),
('Southend-on-Sea','United Kingdom'),
('Cape Coral','United States'),
('Dresden','Germany'),
('Wiesbaden','Germany'),
('Changping','China'),
('Charleston','United States'),
('Palu','Indonesia'),
('Taizhou','China'),
('Xiangtai','China'),
('Samsun','Turkey'),
('Luxor','Egypt'),
('Belgaum','India'),
('Pontianak','Indonesia'),
('Yaroslavl','Russia'),
('Constantine','Algeria'),
('Bandjarmasin','Indonesia'),
('Abu Dhabi','United Arab Emirates'),
('Mission Viejo','United States'),
('Kirkuk','Iraq'),
('Sangli','India'),
('Barcelona','Venezuela'),
('Canoas','Brazil'),
('El Mansura','Egypt'),
('Sohag','Egypt'),
('Barnaul','Russia'),
('Zahedan','Iran'),
('Jalalabad','Afghanistan'),
('Chiclayo','Peru'),
('Albany','United States'),
('Hermosillo','Mexico'),
('Port Louis','Mauritius'),
('Grand Rapids','United States'),
('Chandrapur','India'),
('Al Hillah','Saudi Arabia'),
('Al Hillah','Iraq'),
('Rasht','Iran'),
('Nagano','Japan'),
('Vinh','Vietnam'),
('Abeokuta','Nigeria'),
('Kayseri','Turkey'),
('Samarinda','Indonesia'),
('Ajmer','India'),
('Baton Rouge','United States'),
('Dortmund','Germany'),
('Vladivostok','Russia'),
('Irkutsk','Russia'),
('Blantyre','Malawi'),
('Knoxville','United States'),
('Anqing','China'),
('Cuttack','India'),
('Hachioji','Japan'),
('Khabarovsk','Russia'),
('Veracruz','Mexico'),
('Kisangani','Congo (Kinshasa)'),
('Libreville','Gabon'),
('Kerman','Iran'),
('Urmia','Iran'),
('Bikaner','India'),
('Quetzaltenango','Guatemala'),
('Shihezi','China'),
('Ogden','United States'),
('Columbia','United States'),
('Kuching','Malaysia'),
('Shuozhou','China'),
('Niigata','Japan'),
('Pereira','Colombia'),
('Macau','Macau'),
('Bakersfield','United States'),
('Bouake','C𴥠DӉvoire'),
('Akron','United States'),
('Binjai','Indonesia'),
('Manama','Bahrain'),
('Uberlandia','Brazil'),
('New Haven','United States'),
('Sorocaba','Brazil'),
('Tongling','China'),
('Weihai','China'),
('Mar del Plata','Argentina'),
('Santiago de Cuba','Cuba'),
('Siping','China'),
('Kagoshima','Japan'),
('Surakarta','Indonesia'),
('Makhachkala','Russia'),
('Bhavnagar','India'),
('Uyo','Nigeria'),
('Bristol','United Kingdom'),
('Bahawalpur','Pakistan'),
('Kenitra','Morocco'),
('Ribeirao Preto','Brazil'),
('Kanazawa','Japan'),
('Orenburg','Russia'),
('Malaga','Spain'),
('Tabuk','Saudi Arabia'),
('Puerto la Cruz','Venezuela'),
('Jiujiang','China'),
('Hisar','India'),
('Kashgar','China'),
('Matola','Mozambique'),
('Bilaspur','India'),
('Sargodha','Pakistan'),
('Leipzig','Germany'),
('Vilnius','Lithuania'),
('Tirunelveli','India'),
('Cancun','Mexico'),
('Yangzhou','China'),
('Novokuznetsk','Russia'),
('Al Ladhiqiyah','Syria'),
('Matamoros','Mexico'),
('Goteborg','Sweden'),
('Otsu','Japan'),
('Tomsk','Russia'),
('Linxia','China'),
('Matsuyama','Japan'),
('Rouen','France'),
('Jiangmen','China'),
('Oaxaca','Mexico'),
('Beira','Mozambique'),
('Guntur','India'),
('Trablous','Lebanon'),
('Hamadan','Iran'),
('Cangzhou','China'),
('Kota Kinabalu','Malaysia'),
('Gold Coast','Australia'),
('Jian','China'),
('Londrina','Brazil'),
('Ryazan','Russia'),
('Shashi','China'),
('Bello','Colombia'),
('Tyumen','Russia'),
('Lipetsk','Russia'),
('Siliguri','India'),
('Eskisehir','Turkey'),
('Banda Aceh','Indonesia'),
('Ujjain','India'),
('Salta','Argentina'),
('Penza','Russia'),
('Blida','Algeria'),
('Mykolayiv','Ukraine'),
('Karbala','Iraq'),
('Suez','Egypt'),
('Gliwice','Poland'),
('Bukittinggi','Indonesia'),
('Liaoyuan','China'),
('Kota Baharu','Malaysia'),
('Jundiai','Brazil'),
('Edinburgh','United Kingdom'),
('Tlaxcala','Mexico'),
('Arak','Iran'),
('Davangere','India'),
('Vina del Mar','Chile'),
('Pingtung','Taiwan'),
('Annaba','Algeria'),
('Akola','India'),
('Brighton','United Kingdom'),
('Astrakhan','Russia'),
('Bradford','United Kingdom'),
('Provo','United States'),
('Bari','Italy'),
('Mazatlan','Mexico'),
('Awka','Nigeria'),
('San Lorenzo','Paraguay'),
('Taoyuan','Taiwan'),
('Chiayi','Taiwan'),
('Keelung','Taiwan'),
('Thai Nguyen','Vietnam'),
('Shuangyashan','China'),
('El Minya','Egypt'),
('Damanhur','Egypt'),
('Pasuruan','Indonesia'),
('Tsu','Japan'),
('Mataram','Indonesia'),
('Macapa','Brazil'),
('Reynosa','Mexico'),
('Shahrisabz','Uzbekistan'),
('Douma','Syria'),
('Worcester','United States'),
('Skopje','Macedonia'),
('Mwanza','Tanzania'),
('Wuwei','China'),
('Toledo','United States'),
('Port Sudan','Sudan'),
('Santa Fe','Argentina'),
('Tula','Russia')`;